version: "2.2"
services:
  notification_manager:
    container_name: notification_service
    image: notification_service
    build:
      context: .
    depends_on:
      notification_manager_db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget localhost:${SERVER_PORT}/health/ping -q -O - > /dev/null 2>&1"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - DB_HOST=notification_manager_db
      - DB_PORT
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - SERVER_PORT
      - SENDGRID_API_KEY
      - SENDGRID_VERIFIED_SENDER
      - TWILIO_ACCOUNT_SID
      - TWILIO_AUTH_TOKEN
      - TWILIO_SENDER_PHONE
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
  notification_manager_db:
    container_name: notification_manager_db
    image: postgres:12-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username ${DB_USER} --dbname ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - notification_manager_db_volume:/var/lib/postgresql/data
      - ./scripts/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "${DB_PORT}:5432"
volumes:
  notification_manager_db_volume: