version: "2.2"
services:
  notification_service:
    image: notification_service
    container_name: notification_service
    build:
      context: .
    environment:
      - SERVER_PORT
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"